#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -z "${1:-}" ]]; then
    aws cognito-idp list-users --user-pool-id "${USR_POOL_ID}" | jq 'reduce .Users[] as $ele ({}; .[$ele.Username] = $ele)'
    return $?
  fi

  local nm_user="${1}"; shift 

  local json_get_user="$(jq -n --arg username "${nm_user}" '{ UserPoolId: env.USR_POOL_ID, Username: $username }')"

  if [[ -z "${1:-}" ]]; then
    set -- .
  fi

  exec aws cognito-idp admin-get-user --cli-input-json "${json_get_user}" | jq -r "$@"
}

source sub "$BASH_SOURCE" "$@"
