#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_usr="0.0.1"
  jq -n --arg usr "$ver_usr" '{usr: $usr}'
}

version "$@"
